CREATE TABLE movies (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  title VARCHAR(45) NOT NULL,
  genre VARCHAR(45) NOT NULL,
  image VARCHAR(1000) NOT NULL,
  category VARCHAR(45) NOT NULL,
  year INT DEFAULT NULL
 ); 

CREATE TABLE users (
idUsers INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
user VARCHAR(45) NOT NULL,
password VARCHAR(45) NOT NULL,
name VARCHAR(45) NOT NULL,
email VARCHAR(45) NOT NULL,
plan_details VARCHAR(45) NOT NULL
);

CREATE TABLE actors (
 idActor INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  lastname VARCHAR(45) NOT NULL,
  country VARCHAR(45) NOT NULL,
  year_birthday INT NULL
); 
